m = 17 % 9 + 1
print(m)
print('   _~_     ' * int(m), end = '  \n')
print('  (o o)    ' * int(m), end = '  \n')
print(' /  V  \   ' * int(m), end = '  \n')
print('/(  +  )\  ' * int(m), end = '  \n')
print('  ^^ ^^    ' * int(m), end = '  \n')
print('  ``````   ' * int(m), end = '  \n')
n = 3 % 9 + 1
print(n)
print('   _~_     ' * int(n), end = '  \n')
print('  (o o)    ' * int(n), end = '  \n')
print(' /  V  \   ' * int(n), end = '  \n')
print('/(  +  )\  ' * int(n), end = '  \n')
print('  ^^ ^^    ' * int(n), end = '  \n')
print('  ``````   ' * int(n), end = '  \n')
print('-Ля какие!')
